### PR TITLE
Enable Cross-Compiling support

### PR DESCRIPTION
**Pull request by kleetus**
1. To use this feature, set CC and CXX env variables to the appropriate cross compiler
2. Example, for cross compiling to ARM, use: CC=arm-linux-gnueabihf-gcc-4.9 CXX=arm-linux-gnueabihf-g++-4.9 npm install
3. You can still compile without setting CC and CXX, you can still just run npm install

### CODE REVIEW

**Comment by braydonf** [comment]
Tested standard build on linux x64, and everything went well (as similar to travis build). Testing cross-compilation now.

We should also add a note to https://github.com/bitpay/bitcore-node/blob/master/docs/build.md for cross compiling (similar to the note in the PR description).

**Comment by braydonf** [comment]
Cross compiling with these commands worked here:
```
export CC=arm-linux-gnueabihf-gcc-4.8
export CXX=arm-linux-gnueabihf-g++-4.8
npm install
```

**Comment by braydonf** [comment]
LGTM

**Comment by ralphtheninja** [comment]
@kleetus This module would be perfect to have prebuilt binaries for

**Comment by kleetus** [comment]
There are prebuilt binaries already available. When doing an npm install, the build scripts will gather the binary from our s3 repo. If you mean prebuilt binaries in terms of a deb package, this is coming as well.

**Pull request merged**
