### PR TITLE
Typo "to" >= "from"

### PR DESCRIPTION
**Pull request by carnesen**

### CODE REVIEW

**Comment by maraoz** [comment]
not a typo... `"to" must be >= to "from"'` reads `"to" must be greater than or equal to "from"`

**Comment by maraoz** [comment]
can we close this_

**Comment by carnesen** [comment]
Javascript I'm still a newbie but I definitely claim technical writing as one of my qualifications :) I for one read it as "to must be greater than or equal to to from", which actually had me scratching my head for a couple seconds. Certainly I'd say that "greater than or equal to" is the more natural reading of the symbol combination ">=" without any need for explicit prepositions. Funny because that comment is unnecessary in the first place; the logic is immediately clear from the code.

**Comment by maraoz** [comment]
You convinced me :)
It's not a comment though, it's an error message for the user!

**Comment by carnesen** [comment]
Right! Thanks. I didn't actually look at the code again this morning and
for some reason it was a comment in my memory.

**Pull request merged**
