### PR TITLE
run address history getDetailedInfo in parallel

### PR DESCRIPTION
**Pull request by mvayngrib**
should speed up `history.get` significantly

### CODE REVIEW

**Comment by braydonf** [comment]
Getting details in parallel, may have some benefit, but only after pagination and with a limit. The trick is that it needs to be in the same order. Getting detailed info before paginating would lead to many expensive calls and work against paginating.

There is also ongoing work in this area with https://github.com/bitpay/bitcore-node/pull/422 that should resolve many issues experienced.

**Comment by mvayngrib** [comment]
@braydonf makes sense, i should have realized that. Why not parallel after `sortAndPaginateCombinedArray`? You'd have to process the results in parallel though, as opposed to pushing to `detailedArray`.

**Comment by braydonf** [comment]
It would be possible, but the results would need to be sorted again afterwards. Each transaction has a few queries running in parallel already for populating previous inputs, so the benefit may not be large. Would need to take a look at performance comparisons.

**Comment by braydonf** [comment]
There may also be a benefit to running a batched query.

**Comment by mvayngrib** [comment]
yep. I was just digging around a bit because i wanted to check an address with a few hundred txs and the response was quite slow. When do you think #422 will land?

**Comment by braydonf** [comment]
@mvayngrib #422 has landed 

Code around this area has changed a lot. There is now a 1-to-1 relationship between transaction and rpc call, so I think it's okay to have concurrency here, and have added concurrent requests for getAddressHistory in https://github.com/bitpay/bitcore-node/pull/449

**Comment by mvayngrib** [comment]
@braydonf great! closing

**Pull request closed without merging**
