### PR TITLE
Performed lexical cast on the reject code instead of using a sprintf.

### PR DESCRIPTION
**Pull request by kleetus**

### CODE REVIEW

**Comment by kleetus** [comment]
closes #191

**Comment by braydonf** [comment]
Do you have a test that covers this case in the regtests?

**Comment by kleetus** [comment]
I will try to add

On Wed, Sep 9, 2015 at 12:59 PM, Braydon Fuller <notifications@github.com>
wrote:

> Do you have a test that covers this case in the regtests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-node/pull/208#issuecomment-138975438>.
>



-- 
Chris Kleeschulte
KK4DYJ


Please note that I only check email twice per day; once at 12pm and at 7pm
US Eastern Time, Monday - Friday. If your email is a true emergency, please
call me at my desk right away. I appreciate your patience.

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFVGpOYBCACWr+/tba3xKXvF77GAFLvpazyNfxsHAbzFLNCV/UgFycKhD5ZY
BbTctpXXKASqfHF7aiTqfQo74catqfCtvMt5zdDwfHdiFvg1M8B6Lsqp4uUU8y/F
nVXDIASEpvdl5Hki8GOVpIwtWiZxMeqPvUGKV0mCelOtvzLILNILjIYnw4YIFrea
UvHAOZ6ggd0xXeqIeSsONgZqDRpLRvDF22kzIlxZE965la6u+k/InYHQJh6Q2tPN
Sk/jW6J06F7mJ7GRBhV9KKFYW9tUTc7CqdhKrN+PNVkXdrGi4j7Zmk3PIBiUHwM2
Cm8+d0rlWqv//UpRJFV2KXAPty2m728AiuMxABEBAAG0JUNocmlzIEtsZWVzY2h1
bHRlIDxsYWNvbmlhQGdtYWlsLmNvbT6JATgEEwECACIFAlVGpOYCGwMGCwkIBwMC
BhUIAgkKCwQWAgMBAh4BAheAAAoJEEVidVpzVuRYFGMH/0Fybe0S6gdhXnm6ofEJ
RrU+oC+ufD3QEo5YHcHPEjgvt+x4fBLBSXZAnulNdzwacf2yqonNU5T8JtlX2cr3
swBvpfbdVGUDpSWt1anBoTJ+lFbUE/DkYHCIdcZeCCqO/gJdSNn3KxxvVE/g3pDN
xAYATWoopfG0U8xCLgQbV+cC0qTDfkSj1BZOHISMIoshXmkaZfWrH+oUMBK/Dw1C
0Zp6NDPgme/E6p2D0o3xjQpSy4mPd/1Bq6AsD5I2SoHXwLU5V7O1b+o8/9yrMUkv
jArEE4aLeTD6FxUNfRehDYeWuStp1sczWsG3ZngQwaaBWayey2kweD1AmQ941NN5
Jp+5AQ0EVUak5gEIAJ/IyDrwwY4i4XuLVX/bRMIS+7dJHJh19hkvhbTOynIrXQcl
sbJI/l9uDDGTbRDORUGvwQLOAFU/xvXNMb/CuESThvdcRBAq7sVGIjOl22itF+Wc
BslXWWAfnuHmw1CZ5N3qXbUG7zvuti/Wgg5bZj6Gfld41mNP3V2juFPIcs/pyKtf
hcJ92/TppuxC4DIqlugBk+51jAoSVJb8814A8hqlcndtMzb8Xt0+T8vqPS4aSjkz
MS42ijQpXFv3LJCTGrwSJbsMj+GHb0Lw+a+bFqbp6LE2g5fJiKPZUoGNSsa+/J3n
hP3qFTPuib7awZIQFp281lICsYmRNCGWe+gYNZkAEQEAAYkBHwQYAQIACQUCVUak
5gIbDAAKCRBFYnVac1bkWHhLB/0WvIzS+8pNmLmlgtVbMyQtlNAkmSnamYom+8jL
DdhHd4s1xc3i1ACQLzfojuYFvFWEt5pIS15Qdvu+31SJ03VY/jaYW0nycdb+W8wD
rg53PBrChka7j6Lg1ANKFJq1s7cMVyvumAXPqjjjDGIh021im+WhNDvLGi2BCW17
50a4YL6Iv7q76z6rqbgh1txbZ5QLJXX11xtikiD2SGxACoYAxIjFl+lyZI7SIX5h
dhOfNdwAYnfEWimKl4NCGtQC7lE9dPfDya2lk+FxJQpl/lmJTspAt43kBMoYZ4xG
MDAO12PmRSQHhqfVgwHX0f2Y11PC011vd0fTlhOtxdARiA20
=L/YR
-----END PGP PUBLIC KEY BLOCK-----

**Comment by braydonf** [comment]
Great work, looks good to me.

**Pull request merged**
