### PR TITLE
Fixing #363

### PR DESCRIPTION
**Pull request by Levino**
Breaking API! Modified tests!

See issue for details. Currently deployed here: https://insight-testnet.satoshipay.io/insight-api/addr/xxx and here: https://insight.satoshipay.io/insight-api/addr/xxx

### CODE REVIEW

**Comment by Levino** [comment]
There should be a specific test, I suggest. But I do not really get what is going on in the test file (what exactly is being simulated)

**Comment by braydonf** [comment]
Related: https://github.com/bitpay/bitcore-node/pull/341

**Comment by braydonf** [comment]
Since this was changed recently for compatibility, I don't see changing it back. Perhaps the same goal can be accomplished another way.

**Comment by Levino** [comment]
Dear @braydonf I understand. But I fear it has been changed in a matter that makes no sense. If you could, please give a verbal definition of what the value should return for any given set of confirmed and unconfirmed transactions.

**Comment by braydonf** [comment]
Let's revisit this when we work on the next version iteration (with breaking changes) of the Insight API, and clarify the meaning of unconfirmed.

**Comment by Levino** [comment]
Agreed. Sorry for the additional commits, they had nothing to do with this repo.

**Comment by braydonf** [comment]
I'm not sure when. I think some of the architecture that was started here: https://github.com/bitpay/bitcore-node/blob/v0.1.0/api/routes/v1.js is decent, and results are returned in `bitcore.toJSON()` format which makes reconstructing a bitcore object on the other side able to be built-in. It may also be worth taking a look at something like gRPC, and with the already available methods from each service.

**Pull request closed without merging**
