### PR TITLE
WIP Change to use bitcore as a peerDependency.

### PR DESCRIPTION
**Pull request by braydonf**
From tests using peerDependency will install the dependency with a global install, however when required in a package.json it will give a warning that a dependency isn't meet.

### CODE REVIEW

**Comment by braydonf** [comment]
Actually, looks like it's not installed (as from the tests).

**Comment by fanatid** [comment]
@braydonf I had a same problem with travis, you need install bitcore with separate command... [my travis config](https://github.com/fanatid/coloredcoinjs-lib/blob/master/.travis.yml#L16)

**Comment by braydonf** [comment]
It looks like the behavior of the global install is similar. e.g. `npm install -g bitcore-node` would also need to have a `npm install -g bitcore`?

**Comment by fanatid** [comment]
I don't know about global installation behavior, but think that `npm install -g bitcore-node` required `npm install -g bitcore`.

**Comment by braydonf** [comment]
Yep, however the CLI tool itself doesn't need bitcore, and will actually find a locally installed bitcore-node and and bitcore-node.json and run that rather than the global version. So it could be possible to globally install the CLI via something like `npm install -g bitcore-node-cli`. Which can then be used to configure and setup packages and services for a node.

**Comment by braydonf** [comment]
I'll reopen to discuss.

**Comment by fanatid** [comment]
`npm install -g bitcore-node-cli` is nice!
Also you can try `install` from [scripts](https://docs.npmjs.com/misc/scripts) (put `npm install bitcore` to there), but as I understand it's broke node_modules that related with package that use `bitcore-node`.

**Pull request closed without merging**
