### PR TITLE
Crash on reindex

### PR DESCRIPTION
**Pull request by kleetus**
- Added the concept of loadingServices on the node so that the node can conditionally call stop on loadingServices
- This serves the case where services might be loading versus fully loaded (which is not always the cases for heavy services like bitcoind)

### CODE REVIEW

**Comment by braydonf** [comment]
If we're stop is going to be called an a service that hasn't yet started, couldn't that cause issues? I think it makes sense for have the start callback exit, if the node is shutdown.

**Comment by kleetus** [comment]
closes #218

**Comment by kleetus** [comment]
I think, although this change is not the best (due to the fact that it requires the services to handle their own state with respect to stopping), it is better than without this change. 

I think, in the future, it would be best to ask the services to manage their own states. For example, if stop is called whilst they are in a startup state, the services would know best if they can stop or not.

**Comment by braydonf** [comment]
Adding the service into the node.services object before it's started would achieve the same result, without needing to have `_loadingServices`.

**Comment by braydonf** [comment]
Tested, and this fixes the issue.

**Pull request merged**
