### PR TITLE
DB: export getBlockIndex and getBestBlockHash

### PR DESCRIPTION
**Pull request by jpochyla**
Simply exporting two methods of `bitcoind` service through DB. I needed this for partial transaction history update.

### CODE REVIEW

**Comment by braydonf** [comment]
It may be better to export these from the bitcoind service?

**Comment by jpochyla** [comment]
bitcoind seems like the right place, but the service has no exported methods, and doesn't depend on the web service. DB already wraps other bitcoind functionality, so I thought it would fit in.

**Comment by jpochyla** [comment]
Hi, any update on this? I think the failing test is non-deterministic and not caused by this pull-request.

**Comment by braydonf** [comment]
Yep, looks like there is a test that is non-deterministic, tests passing. 

We may want to move existing wrapped functionality of bitcoind to the bitcoind service as well at some point, and add a few exported methods. This may make sense now that we may have a few more being added. Thoughts? @kleetus @pnagurny @bitjson

**Comment by jpochyla** [comment]
Sorry about the long wait! We ended up using the REST endpoints from insight-api. I'll close this, as we no longer need a fork and others don't seem to be interested.

**Pull request closed without merging**
