### PR TITLE
Fix #380. Add missing git config properties if required before committing bitcoin core patch.

### LINKED ISSUE #380: FIXED in #383 - npm install fails when missing global git config
```sh
% git clone https://github.com/bitpay/bitcore-node.git
...
% cd bitcore-node
% npm install -g
...
HEAD is now at 7e27892... Merge pull request #6975
../patch-bitcoin.sh /.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/bin/../libbitcoind
Switched to a new branch 'libbitcoind-2015.12.18'
patching file config_me.sh
patching file configure.ac
patching file depends/hosts/linux.mk
patching file depends/packages/bdb.mk
patching file depends/packages/boost.mk
patching file src/Makefile.am
patching file src/bitcoind.cpp
patching file src/init.cpp
patching file src/init.h
patching file src/main.cpp
patching file src/net.cpp
patching file src/net.h
patching file src/txmempool.cpp

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <bc@574e3f2df4c7.(none)>) not allowed
...
```

This, of course, can be  worked around by preempting the `npm install` command with the appropriate `git config --global` commands. However, since it's a build process internal to bitcore-node, it probably should not require the installer to set a global config for a one-off commit for an internal clone of the bitcoin core repo. For example, it is unusual for the installing user in a Docker container be required to have a meaningful global `git` configuration.

### PR DESCRIPTION
**Pull request by posita**
Fix #380. Add missing git config properties if required before committing bitcoin core patch.

This only adds the missing properties locally if they are not available globally. In other words, this is useful for installing in environments like Docker containers where the installing user typically does not have a global git configuration. That being said, it should not overwrite or change anything (locally or globally) for users with existing global configurations.

### CODE REVIEW

**Comment by braydonf** [comment]
We shouldn't need to set this in `travis.yml` anymore: https://github.com/bitpay/bitcore-node/blob/master/.travis.yml#L15

**Comment by posita** [comment]
@braydonf, I'll remove it from `travis.yml`. Should I change the [values in `bin/patch-bitcoin`](https://github.com/bitpay/bitcore-node/pull/383/files#diff-3318794d89b1452152493a23ef4803acR28) to match those?

**Comment by braydonf** [comment]
Okay great, I think the values in bin/patch-bitcoin will work, no need to change.

**Comment by posita** [comment]
I think the @braydonf, you might want to try re-running the build without the build cache before merging. I don't see that `patch-bitcoin` is being run (there's no [`Patch completed successfully.` output](https://github.com/posita/bitcore-node/blob/posita/380-add-missing-git-config/bin/patch-bitcoin#L35))

**Comment by braydonf** [comment]
Cleared the build cache, and re-running the tests.

**Comment by posita** [comment]
Ah! I missed two spaces. :disappointed: It should be fixed now. :grimacing:

**Comment by posita** [comment]
This should now patch and build successfully with or without the build cache.

**Comment by braydonf** [comment]
Cleared the build cache, and looks like it's building :) LGTM

**Pull request merged**
