### PR TITLE
Added integration tests for the bus

### LINKED ISSUE #167: Add Bus integration tests
See missed issue, and bug fix: https://github.com/bitpay/bitcore-node/pull/166

### PR DESCRIPTION
**Pull request by kleetus**
- Added a new file that exercises the subscribe/unsubscribe/close methods with a test service
- Removed a duplicate call to inherit

closes #167

### CODE REVIEW

**Comment by braydonf** [comment]
Since this isn't using the regtest feature, could be better in `tests/bus.integration.js` ?

**Comment by kleetus** [comment]
closes #167

**Comment by braydonf** [comment]
Reviewing the differences, and it looks like this functionality is covered in the existing unit test. Or am I missing something?

**Comment by kleetus** [comment]
redoing this test to exercise the bus back to the socket.io level.

**Comment by braydonf** [comment]
Adding a test to integration/regtest-node.js that:
1. Opens a bus from the node using `node.openBus()`
2. Subscribes to `db/transaction` for an address
3. Constructs a transaction to that address and add it to the mempool
4. Using the RPC `client.generate`
5. An event should then be emitted and the bus should have a `db/transaction` event for the address.

I think would cover the case for #167. 

Additional integration tests around the Web Service (and socket.io) could also be added also, but that may be better for another test.

**Comment by kleetus** [comment]
implementing test that Braydon brought up

**Comment by braydonf** [comment]
LGTM

**Pull request merged**
